name: my_weather_app
description: A Flutter application for weather information
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  geolocator: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
